version: '2'
services:
    dlsbackend-app:
        image: dlsbackend
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@dlsbackend-oracle:1521:DlsBackend
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
